### PR TITLE
check privileges before populating cache

### PR DESCRIPTION
**Pull request by nirmoy**

### CODE REVIEW

**Comment by dlipovetsky** [comment]
@nirmoy Thanks for this PR. I apologize for the long delay!

**Comment by nirmoy** [comment]
can't read http://teamcity.platform9.sys:8111/viewLog.html?buildId=805342&buildTypeId=Pf9project_IsvBuilds_IntegrationTests

**Comment by dlipovetsky** [comment]
@nirmoy Sorry, we haven't quite made our builds easy to use externally.

Our "ISV tarball" build invokes `nodeadm download` in a container as non-root user, and this fails with your change.

Although I think it's helpful to have this error, I the above demonstrates the need to be able to ignore it. Ideally, we would have something similar to kubeadm's `--ignore-preflight-errors=...`, but that's a relatively big feature. But we could start with something simpler. What do you think?

**Comment by nirmoy** [comment]
@dlipovetsky  yes sounds good to me :)

**Pull request closed without merging**
